apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: codercomo/app:latest
        ports:
        - containerPort: 5000  # Ensure this matches the port your app is listening on
        env:
        - name: ENVIRONMENT
          value: "production"
