apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "sayedsylvainltd@gmail.com"
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: "Z0532739DYWX1VAIUKTG"
          region: us-east-1
      selector:
        dnsZones:
          - "lab.mohammedsayed.com"
    - http01:
        ingress:
          class: "nginx"
