apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::767398132018:role/eks-cluster-role
      username: admin
      groups:
        - system:masters
