apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argo-cd
  annotations:
    cert-manager.io/cluster-issuer: issuer
spec:
  ingressClassName: nginx  # Ensures it's using the nginx ingress
  rules:
    - host: argocd.lab.mohammedsayed.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server  # Ensure this is the correct service name
                port:
                  number: 80
  tls:
    - hosts:
        - argocd.lab.mohammedsayed.com
      secretName: argocd-ingress-tls



server:
  # to disable SSL redirection. As our ingress controller handles this
  extraArgs:
    - --insecure
  service:
    type: ClusterIP
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.org/hsts: "false"
    cert-manager.io/cluster-issuer: issuer
  hosts:
    - argocd.lab.mohammedsayed.com
  tls:
    - secretName: argocd-ingress-tls
      hosts:
        - argocd.lab.mohammedsayed.com
