name: 'Push docker image to dockerhub'

on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm deployment'
          required: true
          default: 'no'
        

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check if deployment is confirmed
        if: ${{ github.event.inputs.confirmation != 'yes' }}
        run: |
          echo "Deployment not confirmed. Exiting."
          exit 1
    
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Build, tag as latest, and push Docker image to ECR
        id: build-image
        env:
           ECR_REGISTRY: 767398132018.dkr.ecr.us-east-1.amazonaws.com
           ECR_REPOSITORY: mohammedsayed/threat-composer 
        run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
            echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT
      
      - name: Send Discord Notification on Success
        if: success()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ Build and push successful for branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Notification on Failure
        if: failure()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"❌ Build and push failed for branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

  security_scan_app:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Scan Docker image for vulnerabilities (App)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: codercomo/app:latest

      - name: Send Discord Notification on Success
        if: success()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ Security scan successful for app image on branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Notification on Failure
        if: failure()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"❌ Security scan failed for app image on branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

  security_scan_web_fe:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Scan Docker image for vulnerabilities (Web-Fe)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: codercomo/web-fe:latest

      - name: Send Discord Notification on Success
        if: success()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ Security scan successful for web-fe image on branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Notification on Failure
        if: failure()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"❌ Security scan failed for web-fe image on branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

  kubernetes_yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kube-linter
        run: |
          curl -Lo kube-linter.tar.gz https://github.com/stackrox/kube-linter/releases/download/0.2.4/kube-linter-linux.tar.gz
          tar -xzf kube-linter.tar.gz
          sudo mv kube-linter /usr/local/bin/

      - name: Run kube-linter on Kubernetes manifests
        run: |
          kube-linter lint ./k8s-manifests/ || echo "Linting issues found"

      - name: Send Discord Notification on Success
        if: success()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ Kubernetes YAML linting completed for branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Notification on Failure
        if: failure()
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMITTER=${GITHUB_ACTOR}
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"❌ Kubernetes YAML linting failed for branch: ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
