name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build and push the app image
      - name: Build and Push App Image
        run: |
          echo "Building and pushing app image..."
          docker build -t codercomo/app:latest ./app
          docker images | grep codercomo/app
          docker push codercomo/app:latest
        id: build_app_image

      # Discord notification step (refactored)
      - name: Send Discord Notification
        if: always()
        env:
          BRANCH_NAME: "${GITHUB_REF#refs/heads/}"
          TIMESTAMP: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          COMMIT_AUTHOR: "${{ github.event.head_commit.author.name }}"
          COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
          COMMIT_URL: "${{ github.event.head_commit.url }}"
          JOB_STATUS: ${{ job.status }}
          ACTIONS_RUN_URL: "${{ github.run_url }}"
          DOCKER_APP_IMAGE_SIZE: ${{ steps.build_app_image.outputs.size }}
        run: |
          if [[ "$JOB_STATUS" == "success" ]]; then
            STATUS_EMOJI="✅"
            COLOR=3066993  # Green
          else
            STATUS_EMOJI="❌"
            COLOR=15158332 # Red
          fi

          curl -H "Content-Type: application/json" \
          -d "{
                \"embeds\": [{
                  \"title\": \"$STATUS_EMOJI Build and Push Job Result\",
                  \"description\": \"**Branch**: $BRANCH_NAME\n**Commit**: [$COMMIT_MESSAGE]($COMMIT_URL) by $COMMIT_AUTHOR\n**Time**: $TIMESTAMP\n**Docker Image Size**: $DOCKER_APP_IMAGE_SIZE\n**Job Status**: $JOB_STATUS\",
                  \"color\": $COLOR,
                  \"fields\": [
                    { \"name\": \"Logs\", \"value\": \"[View Logs]($ACTIONS_RUN_URL)\" }
                  ]
                }]
              }" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
