apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mo-ASayed/Docker-Kubernetes.git'
    targetRevision: HEAD
    path: k8s-advanced-lab/terraform/app-hub  

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
